services:
  # Development service
  portfolio-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: portfolio-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - WATCHPACK_POLLING=true
    restart: unless-stopped
    profiles:
      - dev

  # Production service
  portfolio-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-prod
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    profiles:
      - prod

  # Default service (development) - using different port to avoid conflicts
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: portfolio-default
    ports:
      - "3002:3000"  # Changed to avoid port conflicts
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - WATCHPACK_POLLING=true
    restart: unless-stopped
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: portfolio-network 