version: '3.8'

services:
  # Development service
  portfolio-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: portfolio-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    profiles:
      - dev

  # Production service
  portfolio-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-prod
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    profiles:
      - prod

  # Default service (development)
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: portfolio-default
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true

networks:
  default:
    name: portfolio-network 